server:
  port: 1560
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.rss.nest
# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn

spring:
  application:
    name: "RSSNest"
  config:
    activate:
      on-profile:
        - dev
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password:
      lettuce:
        pool:
          max-active: 8
          max-wait: 1ms
          max-idle: 8
          min-idle: 0
        shutdown-timeout: 100ms
      timeout: 10000ms
  cache:
    type: redis
    cache-names:
      - USERS
    redis:
      # 缓存过期时间为10*60分钟，单位为毫秒
      time-to-live: 36000000
      # 是否允许缓存空数据，当查询到的结果为空时缓存空数据到redis中
      cache-null-values: true
      # 为Redis的KEY拼接前缀
      key-prefix: "BOOT_CACHE:"
      # 是否拼接KEY前缀
      use-key-prefix: true
      # 是否开启缓存统计
      enable-statistics: false