server:
  port: 1560
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100


spring:
  application:
    name: "RSSNest"
  config:
    activate:
      on-profile:
        - dev