server:
  port: 1560
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.rss.nest
# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn

spring:
  application:
    name: "RSSNest"
  config:
    activate:
      on-profile:
        - dev